Rails.application.config.middleware.use OmniAuth::Builder do
  provider OmniAuth::Strategies::Twitter, 'gcrjiShiA6q4kNMKYflVw', 's30nAtjeNI979fxODuLdFTgiugrwVzX1N3rkF3DE'
  # provider OmniAuth::Strategies::Facebook, ...
  # provider OmniAuth::Strategies::Linkedin, ...
  # provider OmniAuth::Strategies::GitHub, ...
end